### ISSUE TITLE
Actionscript Tracking: Object

### ISSUE THREAD

**Issue by Dinnerbone** [Dinnerbone/ruffle#2]
This is the tracking issue for **Object**. An item will only be checked off once we feel that its both fully implemented and properly tested within our capabilities.

# Object
## Static properties
- [ ] prototype

## Static methods
- [ ] registerClass\(name, theClass\)

## Constructors
- [ ] Object\(\)

## Properties
- [ ] \_\_proto\_\_
- [ ] \_\_resolve
- [ ] constructor

## Methods
- [ ] addProperty\(name, getter, setter\)
- [ ] hasOwnProperty\(name\)
- [ ] isPropertyEnumerable\(name\)
- [ ] isPrototypeOf\(theClass\)
- [ ] toLocaleString\(\)
- [ ] toString\(\)
- [ ] unwatch\(name\)
- [ ] valueOf\(\)
- [ ] watch\(name, callback, userData\)
